name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t alevm98/appdec2 . 

      - name: Push Docker image to DockerHub
        run: docker push alevm98/appdec2:latest

  deploy-to-ec2:
    needs: build-and-push
    runs-on: ubuntu-latest
    strategy:
      matrix:
        instance: ["HOST_DNS", "HOST_DNS2", "HOST_DNS3"]  # Instancias EC2

    steps:
      - name: Trigger redeploy on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets[matrix.instance] }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Este paso solo puede notificar a las instancias EC2 si es necesario (por ejemplo, reiniciar el contenedor)
            echo "La imagen ya está en Docker Hub, las instancias EC2 se encargan del despliegue."
   
  
